from docx import Document
from docx.shared import Pt, Inches, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from datetime import datetime
from pathlib import Path
from rich.console import Console
from src.models import GrantProposal

console = Console()


class DocxExporter:
    """Export grant proposals to Word documents"""
    
    def __init__(self):
        self.output_dir = Path("outputs")
        self.output_dir.mkdir(exist_ok=True)
    
    def create_document(self, proposal: GrantProposal) -> str:
        """Create a formatted Word document from grant proposal"""
        console.print("\n[bold blue]📄 Creating Word document...[/bold blue]")
        
        doc = Document()
        
        # Set up styles - apply font settings to paragraphs instead
        # (document-level style modification can have type issues)
        
        # Title page
        title = doc.add_heading(f'{proposal.grant_type} Grant Proposal', 0)
        title.alignment = WD_ALIGN_PARAGRAPH.CENTER
        
        # Company name
        company = doc.add_paragraph(proposal.company_name)
        company.alignment = WD_ALIGN_PARAGRAPH.CENTER
        company.runs[0].font.size = Pt(16)
        company.runs[0].font.bold = True
        
        # Date
        date_para = doc.add_paragraph(f"Generated: {proposal.created_at.strftime('%B %d, %Y')}")
        date_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        date_para.runs[0].font.size = Pt(10)
        date_para.runs[0].font.color.rgb = RGBColor(128, 128, 128)
        
        doc.add_page_break()
        
        # Table of Contents
        doc.add_heading('Table of Contents', 1)
        toc_items = [
            "1. Project Pitch",
            "2. Technical Objectives",
            "3. Broader Impacts",
            "4. Commercialization Plan"
        ]
        for item in toc_items:
            doc.add_paragraph(item, style='List Bullet')
        
        doc.add_page_break()
        
        # Add each section
        sections = [
            (1, "Project Pitch", proposal.project_pitch),
            (2, "Technical Objectives", proposal.technical_objectives),
            (3, "Broader Impacts", proposal.broader_impacts),
            (4, "Commercialization Plan", proposal.commercialization_plan)
        ]
        
        for num, title, section in sections:
            # Section heading
            heading = doc.add_heading(f'{num}. {title}', 1)
            
            # Section content
            paragraphs = section.content.split('\n\n')
            for para_text in paragraphs:
                if para_text.strip():
                    # Check if it's a subheading (starts with # or is all caps)
                    if para_text.strip().startswith('#'):
                        # Remove # and add as subheading
                        clean_text = para_text.strip().lstrip('#').strip()
                        doc.add_heading(clean_text, 2)
                    else:
                        para = doc.add_paragraph(para_text.strip())
                        para.paragraph_format.space_after = Pt(6)
                        para.paragraph_format.line_spacing = 1.15
            
            # Add page break after each section except the last
            if num < 4:
                doc.add_page_break()
        
        # Footer with metadata
        section = doc.sections[0]
        footer = section.footer
        footer_para = footer.paragraphs[0]
        footer_para.text = f"Generated by Grantentic | Total words: {proposal.total_word_count:,} | Cost: ${proposal.total_cost:.2f}"
        footer_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        footer_para.runs[0].font.size = Pt(8)
        footer_para.runs[0].font.color.rgb = RGBColor(128, 128, 128)
        
        # Save document
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"{proposal.company_name.replace(' ', '_')}_NSF_SBIR_Phase1_{timestamp}.docx"
        filepath = self.output_dir / filename
        
        doc.save(str(filepath))
        
        console.print(f"[green]✓ Document saved to: {filepath}[/green]")
        console.print(f"[cyan]📊 Total words: {proposal.total_word_count:,}[/cyan]")
        
        return str(filepath)
